### ISSUE TITLE
Error trying to enable development mode

### ISSUE THREAD

**Issue by ilson-nobrega** [zfcampus/zf-development-mode#15]
Hello,
I'm using the latest version of module. But, when i try to enable development mode i get an error, see:
![image](https://cloud.githubusercontent.com/assets/7192737/11378388/0c076540-92d2-11e5-9efe-b1cb02ed31e5.png)

I'm using zf-apigility-doctrine into my project.

As I could see, the Zend first load the Doctrine libraries (which returns the aforementioned error) before loading the DevelopmentMode class.

Is there a way to suppress premature loading of the Doctrine? (Premature because the developer has not configured the database connection).
And the only way to make it work is going manually and retitle the .dist files.

Thanks for the attention,

Ilson Nóbrega

**Comment by clemf** [comment]
I'm having the same issue. Development mode does not appear to work with Doctrine:

```sh
php public/index.php development enable

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Users/clemfreeman/Code/secretary/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /Users/clemfreeman/Code/secretary/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'xyz', 'abc', Array)
#1 /Users/clemfreeman/Code/secretary/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'xyz', 'abc', Array)
#2 /Users/clemfreeman/Code/secretary/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'xyz', 'abc', Array)
#3 /Users/clemfreeman/Code/secretary/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /Users/clemfreeman/Code/secretary/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatfo in /Users/clemfreeman/Code/secretary/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930
```

**Comment by weierophinney** [comment]
This might be related to #16 (configuration caching). Can you update to v2.1.2 and see if the issue is resolved, please?

**Comment by clemf** [comment]
@weierophinney I was getting this issue after moving my development doctrine `connection` configuration into `config/autoload/devlopment.local.php`. When I manually enable that configuration, `development enable` works fine, but otherwise it exits with the `PDOException`. 2.1.2 has the same behavior.

Before adding Apigility to our ZF2 project, we were using an environment variable check to enable development configuration, as [described in the documentation](http://framework.zend.com/manual/current/en/tutorials/config.advanced.html#environment-specific-system-configuration). For now I'll go back to that method. Is there a reason that development mode has to run the application? At the stage in my application setup process that `development enable` is useful I do not yet have my vagrant environment up.

**Comment by weierophinney** [comment]
> Is there a reason that development mode has to run the application?

It no longer does, as of v3.0.0, which uses zf-console, instead of the zend-mvc console integration, to do the work. Try upgrading to that version; however, be aware that the invocation of the tool changes when you do (see [the migration note](https://apigility.org/documentation/modules/zf-development-mode#note-to-v2-users) for details).
